### ISSUE TITLE
Allows to define testing specification via `TESTBENCH_SPECIFICATION` environment variable

### ISSUE THREAD

**Issue by crynobone** [orchestral/testbench-core#293]
I always wanted to be able to run tests in different specifications such as with and without immutable date.

```yaml
      - name: Execute tests
        run: vendor/bin/phpunit

      - name: Execute tests (Immutable Dates)
        run: vendor/bin/phpunit
        env:
          TESTBENCH_SPECIFICATION: 'immutable-date'
```
